import {test,expect} from '@playwright/test';
test('stage fills the viewport with the selected palette and follows daylight in 2D and 3D',async({page})=>{
  await page.goto('/demo/');await page.waitForFunction(()=>!document.documentElement.hasAttribute('data-loading'));
  const card=page.locator('floorplan-card');
  const sun=async elevation=>page.evaluate(e=>{const c=document.querySelector('floorplan-card');c.hass={...c._hass,states:{...c._hass.states,'sun.sun':{state:e>0?'above_horizon':'below_horizon',attributes:{elevation:e}}}};},elevation);
  await card.getByRole('button',{name:'2D',exact:true}).click();await sun(-10);
  const stage=card.locator('.plan-slot'),shade=card.locator('[data-room-shade]').first();
  const night=await stage.evaluate(n=>getComputedStyle(n).backgroundColor),dark=Number(await shade.getAttribute('fill-opacity'));
  await sun(40);
  await expect.poll(()=>shade.getAttribute('fill-opacity')).not.toBe(String(dark));
  expect(Number(await shade.getAttribute('fill-opacity'))).toBeLessThan(dark);
  await expect.poll(()=>stage.evaluate(n=>getComputedStyle(n).backgroundColor)).not.toBe(night);
  await card.getByRole('combobox',{name:'Custom style',exact:true}).selectOption('pokemon');
  await expect(stage).toHaveCSS('background-color','rgb(137, 173, 131)');
  await expect(card.locator('.plan')).toHaveCSS('background-color','rgb(137, 173, 131)');
  await card.getByRole('button',{name:'3D',exact:true}).click();await sun(-10);
  const canvas=card.locator('canvas');await expect(canvas).toBeVisible();
  const before=await canvas.screenshot();await sun(40);
  await expect(stage).toHaveCSS('background-color','rgb(220, 231, 224)');
  expect((await canvas.screenshot()).equals(before)).toBe(false);
});
