import {test,expect} from '@playwright/test';
test('furniture and lights place by click and centre without randomUUID',async({page})=>{
  await page.addInitScript(()=>Object.defineProperty(crypto,'randomUUID',{value:undefined,configurable:true}));
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/demo/');await page.waitForFunction(()=>!document.documentElement.hasAttribute('data-loading'));
  await page.getByRole('button',{name:'Edit layout',exact:true}).click();const editor=page.locator('floorplan-card-editor');
  await editor.getByRole('button',{name:'Unlock editing',exact:true}).click();
  const counts=()=>editor.evaluate(e=>[e.config.floors[0].objects.length,e.config.floors[0].entities.length]);const before=await counts();
  await editor.getByLabel('Find furniture').fill('piano');
  await editor.locator('.furniture-palette').getByRole('button',{name:'Piano',exact:true}).click();
  await editor.getByRole('button',{name:'Place furniture in centre',exact:true}).click();
  await editor.getByRole('button',{name:'Add furniture',exact:true}).first().click();
  await editor.locator('.furniture-palette').getByRole('button',{name:'Piano',exact:true}).click();
  await editor.locator('.furniture-canvas .plan').click({position:{x:30,y:30}});
  await expect.poll(async()=>(await counts())[0]).toBe(before[0]+2);
  await editor.getByRole('button',{name:'4. Lights & sensors',exact:true}).click();
  await editor.getByRole('button',{name:'Spotlight',exact:true}).click();await editor.getByRole('button',{name:'Place in centre',exact:true}).click();
  await editor.getByRole('button',{name:'Pendant light',exact:true}).click();await editor.locator('.plan').click({position:{x:30,y:30}});
  await expect.poll(async()=>(await counts())[1]).toBe(before[1]+2);
  expect(errors).toEqual([]);
});
