import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('custom furniture sprites fit their footprint and are included in exports',async({page})=>{
  await page.goto('/demo/');await page.getByRole('button',{name:'Edit layout',exact:true}).click();
  const editor=page.locator('floorplan-card-editor');
  await editor.getByRole('button',{name:'3. Furniture',exact:true}).click();
  await editor.getByRole('button',{name:'Unlock editing',exact:true}).click();
  await editor.getByRole('combobox',{name:'Placed furniture',exact:true}).selectOption({index:1});
  const before=JSON.parse(await page.locator('#config').textContent()).floors[0].objects[0];
  await editor.getByText('Custom pixel artwork',{exact:true}).click();
  await editor.getByLabel('Pokémon furniture sprite',{exact:true}).setInputFiles('demo/sample.svg');
  await expect(editor.getByRole('button',{name:'Remove Pokémon sprite',exact:true})).toBeVisible();
  const after=JSON.parse(await page.locator('#config').textContent()).floors[0].objects[0];
  expect(after).toMatchObject({x:before.x,y:before.y,width:before.width,depth:before.depth});
  expect(after.style_images.pokemon).toMatch(/^data:image\/svg\+xml;base64,/);
  await editor.getByRole('button',{name:'6. Review',exact:true}).click();
  await editor.getByRole('combobox',{name:'Render style',exact:true}).selectOption('pokemon');
  await page.getByRole('button',{name:'Live view',exact:true}).click();
  await expect(page.locator('floorplan-card').locator('[data-private-sprite]').first()).toHaveAttribute('preserveAspectRatio','xMidYMid meet');
  await page.getByRole('button',{name:'Edit layout',exact:true}).click();await editor.getByRole('button',{name:'Import / export',exact:true}).click();
  const download=page.waitForEvent('download');await editor.getByRole('button',{name:'Export full configuration',exact:true}).click();
  const exported=JSON.parse(await readFile(await (await download).path(),'utf8'));
  expect(exported.floors[0].objects[0].style_images).toEqual(after.style_images);
});
import {normaliseConfig} from '../src/lights.js';
test('private style artwork uploads without moving geometry and exports portably',async({page})=>{
  await page.goto('/demo/');await page.getByRole('button',{name:'Edit layout',exact:true}).click();
  const editor=page.locator('floorplan-card-editor');
  const before=normaliseConfig(JSON.parse(await page.locator('#config').textContent()));
  await editor.getByRole('button',{name:'6. Review',exact:true}).click();
  await editor.getByText('Use your own Pokémon or Zelda artwork',{exact:true}).click();
  await editor.getByLabel('Pokémon background',{exact:true}).first().setInputFiles('demo/sample.svg');
  await expect(editor.getByRole('button',{name:'Remove Pokémon background',exact:true})).toBeVisible();
  const after=JSON.parse(await page.locator('#config').textContent());
  expect(after.floors[0].style_images.pokemon).toMatch(/^data:image\/svg\+xml;base64,/);
  expect(after.floors[0].rooms).toEqual(before.floors[0].rooms);
  expect(after.floors[0].objects).toEqual(before.floors[0].objects);
  await editor.getByRole('combobox',{name:'Render style',exact:true}).selectOption('pokemon');
  await page.getByRole('button',{name:'Live view',exact:true}).click();
  await expect(page.locator('floorplan-card').locator('svg.floor-image image').first()).toHaveAttribute('href',after.floors[0].style_images.pokemon);
  await page.getByRole('button',{name:'Edit layout',exact:true}).click();
  await editor.getByRole('button',{name:'Import / export',exact:true}).click();
  const download=page.waitForEvent('download');await editor.getByRole('button',{name:'Export full configuration',exact:true}).click();
  const saved=await download;const exported=JSON.parse(await readFile(await saved.path(),'utf8'));
  expect(exported.floors[0].style_images.pokemon).toEqual(after.floors[0].style_images.pokemon);
  expect(exported.floors[0].image).toMatch(/^data:image\//);
});
