export const styles = `
:host{display:block;color:var(--primary-text-color,#26343d);font-family:var(--paper-font-body1_-_font-family,system-ui)}
*{box-sizing:border-box}ha-card{display:block;background:var(--ha-card-background,var(--card-background-color,#fff));border-radius:var(--ha-card-border-radius,12px);overflow:hidden;border:1px solid var(--divider-color,#dce2e6)}
header,.controls,.editor{padding:16px}h2{font-size:20px;margin:0 0 12px}p{line-height:1.5;margin:8px 0;font-size:14px}.muted{color:var(--secondary-text-color,#607078)}
.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}button,select,input{font:inherit}button{min-height:44px;padding:8px 12px;border-radius:8px;border:1px solid var(--divider-color,#d0d9dd);color:inherit;background:var(--secondary-background-color,#f5f7f8);cursor:pointer}button[aria-pressed=true],button.active{background:var(--primary-color,#007c91);color:var(--text-primary-color,#fff)}button:disabled{opacity:.45;cursor:default}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--primary-color,#007c91);outline-offset:2px}
.plan{position:relative;margin:12px auto;width:100%;max-width:540px;background:#fff}.floor-image{display:block;width:100%;height:100%}.marker{position:absolute;transform:translate(-50%,-50%);padding:3px;min-width:44px;max-width:45%;min-height:44px;font-size:12px;line-height:1.2;background:#fff;color:#26343d;box-shadow:0 1px 5px #0002}.marker.on{border-color:#d79600;background:#fff0b2}.marker[aria-pressed=true]{outline:3px solid #007c91;background:#e1f5f8;color:#164d58}.marker small{display:block}.marker.sensor{border-radius:6px}.controls{border-top:1px solid var(--divider-color,#dce2e6)}label{display:block;font-size:14px;margin:12px 0}label input:not([type=color]),label select{display:block;width:100%;margin-top:6px}input:not([type=range]),select{min-height:40px;border:1px solid var(--divider-color,#ccd4da);border-radius:6px;padding:6px;background:var(--card-background-color,#fff);color:inherit}input[type=range]{accent-color:var(--primary-color,#007c91)}input[type=color]{display:block;width:100%;margin-top:6px}.error{color:var(--error-color,#b3261e)}.editor .plan{cursor:crosshair}.hint{padding:12px}fieldset{min-width:0;border:1px solid var(--divider-color,#ddd);border-radius:8px;margin:12px 0;padding:10px}legend{font-size:14px}details{margin:12px 0}summary{cursor:pointer;min-height:44px;padding:12px 0}input,select{max-width:100%}.member{justify-content:space-between;margin:8px 0}.member span{overflow-wrap:anywhere;flex:1}.wizard-footer{border-top:1px solid var(--divider-color,#ddd);margin-top:16px;padding-top:16px;justify-content:space-between}.room-status{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:8px;margin-bottom:12px}.room-button{text-align:left}.room-button strong,.room-button small{display:block}.room-button small{margin-top:4px}.room-button:disabled{opacity:1}
/* Shared card and visual-editor surfaces. */
:host{--fp-accent:var(--primary-color,#247d73);--fp-line:var(--divider-color,#dfe6e3);--fp-soft:var(--secondary-background-color,#f3f6f4);--fp-surface:var(--card-background-color,#fff);line-height:1.45}
ha-card{border-color:var(--fp-line);box-shadow:0 5px 24px #203c3510;border-radius:20px}
header{padding:22px 24px 14px}h2{font-size:21px;letter-spacing:-.5px;font-weight:650}h3{font-size:16px;letter-spacing:-.2px;margin:20px 0 10px}
button{display:inline-flex;align-items:center;justify-content:center;gap:7px;border-color:var(--fp-line);background:var(--fp-surface);font-size:13px;font-weight:550;transition:background .15s,box-shadow .15s}
button:hover:not(:disabled){box-shadow:0 2px 8px #243d3215;background:var(--fp-soft)}button[aria-pressed=true]{background:var(--fp-accent);border-color:var(--fp-accent);color:white}button[aria-pressed=true]:hover{background:var(--fp-accent)}.icon{flex:none;vertical-align:middle}
.view-modes{margin-top:14px;padding-top:14px;border-top:1px solid var(--fp-line);gap:5px}.view-modes button{flex:1;min-width:90px;font-size:11px;padding:7px 5px;border-radius:9px;flex-direction:column;gap:3px}
.plan-slot{padding:0 16px 12px}.plan{max-width:none;background:var(--fp-soft);border-radius:12px;overflow:hidden;margin:0 auto;isolation:isolate}.floor-image{border-radius:12px}.marker{z-index:3;max-width:140px;border-radius:50%;width:38px;height:38px;min-width:38px;min-height:38px;padding:7px;background:#f8faf8;color:#4c6159;box-shadow:0 2px 7px #132b3325}.marker .icon{width:21px;height:21px}.marker.on{background:#fff2bd;color:#8f610b;border-color:#e4c167;box-shadow:0 0 0 5px #ffdc6030,0 2px 6px #132b3325}.marker[aria-pressed=true]{outline:3px solid var(--fp-accent);outline-offset:3px;background:#e7fff6;color:#16584c}.marker.sensor{width:auto;height:auto;min-width:44px;border-radius:20px;gap:4px;white-space:nowrap}.marker.sensor .icon{width:16px}.marker-label{position:absolute;top:calc(100% + 6px);padding:3px 5px;border-radius:5px;background:var(--fp-surface);color:var(--primary-text-color,#26343d);white-space:nowrap;box-shadow:0 2px 5px #0002;font-size:10px}.marker:hover{z-index:6}
.controls{padding:16px 22px;background:var(--fp-surface)}.controls p{font-size:12px}.room-status{grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:6px}.room-button{position:relative;display:block;padding:9px 10px 9px 32px;background:var(--fp-soft);border:0;font-size:12px}.room-button>.icon{position:absolute;left:9px;top:12px;width:16px}.room-button strong{font-size:12px}.room-button small{font-weight:400;font-size:10px;opacity:.8}.empty-plan{text-align:center;padding:52px 25px;background:var(--fp-soft);border-radius:12px}.empty-plan>.icon{width:52px;height:52px;color:var(--fp-accent)}.empty-plan p{max-width:320px;margin:auto;color:var(--secondary-text-color,#607078)}
.editor{padding:22px;background:var(--fp-surface);border:1px solid var(--fp-line);border-radius:18px;min-width:0}.editor>h2{margin-bottom:3px}.editor nav{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px;margin:16px 0}.editor nav button{justify-content:flex-start;padding:9px 8px;font-size:12px}.history-controls{justify-content:flex-end;margin:8px 0}.history-controls button{font-size:11px;min-height:34px}.editor label{font-weight:550;color:var(--primary-text-color,#26343d)}.editor label input,.editor label select{font-weight:400}.editor input:not([type=range]),.editor select{background:var(--fp-soft);border-color:var(--fp-line);border-radius:8px;padding:10px;min-height:44px}.editor input[type=file]{font-size:12px}.editor input[type=file]::file-selector-button{background:var(--fp-surface);border:1px solid var(--fp-line);padding:8px;border-radius:5px;color:inherit;margin-right:8px}.editor .check{display:flex;gap:10px;align-items:center}.editor .check input{width:18px!important;min-height:18px;margin:0!important}.editor fieldset{padding:14px;border-color:var(--fp-line)}.editor legend{font-weight:650;color:var(--fp-accent)}.editor .plan{margin:14px 0}.editor details{border-top:1px solid var(--fp-line);padding-top:4px}.editor summary{font-weight:550;font-size:13px}.furniture-palette{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));max-height:220px;overflow:auto;padding:3px;gap:5px}.furniture-palette button{font-size:11px;min-height:54px;flex-direction:column;padding:7px}.furniture-palette svg{width:38px;height:32px}.object-inspector{background:var(--fp-soft)}.wizard-footer button:last-child{background:var(--fp-accent);color:#fff;border-color:var(--fp-accent)}
@media(max-width:440px){header{padding:16px}.controls,.editor{padding:14px}.plan-slot{padding:0 8px 8px}.marker{min-height:34px;min-width:34px;width:34px;height:34px}.editor nav button{font-size:11px;gap:4px}.editor nav .icon{width:15px}.three-toolbar button{padding:6px;min-width:35px}.view-modes button{min-width:65px}.furniture-palette{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(prefers-reduced-motion:reduce){*{transition:none!important;animation:none!important}}
/* A contained viewing stage keeps tall plans visible without changing their geometry. */
.marker.temperature-marker{width:auto;height:auto;min-width:0;min-height:24px;max-width:none;border:0;border-radius:5px;padding:3px 5px;background:color-mix(in srgb,var(--fp-surface) 82%,transparent);box-shadow:none;color:var(--secondary-text-color,#617269);font-size:10px;font-weight:500;white-space:nowrap}.marker.radiator-control{width:25px;height:25px;min-width:25px;min-height:25px;padding:2px;font-size:15px;border:0;border-radius:5px;background:#ffffff70;box-shadow:none;color:#738178}.marker.radiator-control.heating{color:#bf4334;background:#fff0e4cc}.marker.temperature-marker:hover,.marker.radiator-control:hover{background:var(--fp-surface);box-shadow:0 1px 5px #0002}
:host{container-type:inline-size;--fp-accent:var(--primary-color,#357969);font-family:var(--paper-font-body1_-_font-family,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif)}
.floorplan-dashboard{border-radius:18px;box-shadow:0 8px 36px #193f2d0a}
.card-header{padding:17px 20px 14px;display:flex;align-items:center;gap:10px 18px;flex-wrap:wrap;border-bottom:1px solid var(--fp-line)}
.card-title{display:flex;align-items:center;gap:9px;min-width:120px;margin-right:auto}.card-title>.icon{width:21px;height:21px;color:var(--fp-accent)}.card-title h2{font-size:17px;letter-spacing:-.45px;margin:0;font-weight:650}
.floor-tabs{gap:3px}.floor-tabs button{min-height:36px;font-size:12px;padding:6px 10px;border-color:transparent;border-radius:8px;background:transparent}.floor-tabs button>.icon{width:16px;height:16px}.floor-tabs button[aria-pressed=true]{background:var(--fp-soft);color:var(--fp-accent);border-color:var(--fp-line)}
.card-header .view-modes{margin:0;padding:3px;border:1px solid var(--fp-line);border-radius:10px;background:var(--fp-soft);gap:2px;flex-wrap:nowrap}.card-header .view-modes button{flex:none;min-width:0;min-height:32px;padding:5px 8px;flex-direction:row;border:0;background:transparent;font-size:10px;gap:4px;white-space:nowrap}.card-header .view-modes button>.icon{width:14px;height:14px}.card-header .view-modes button[aria-pressed=true]{background:var(--fp-surface);color:var(--fp-accent);box-shadow:0 1px 4px #173b2e14}
.card-header .view-modes select{appearance:none;-webkit-appearance:none;width:auto;min-width:110px;min-height:32px;margin:0;padding:6px 28px 6px 10px;border:0;border-radius:7px;font-family:inherit;font-size:11px;font-weight:600;line-height:1.3;color:var(--fp-accent);background-color:var(--fp-surface);background-image:linear-gradient(45deg,transparent 50%,currentColor 50%),linear-gradient(135deg,currentColor 50%,transparent 50%);background-position:calc(100% - 14px) 14px,calc(100% - 10px) 14px;background-size:4px 4px;background-repeat:no-repeat;box-shadow:0 1px 4px #173b2e14;cursor:pointer}.card-header .view-modes select:focus-visible{outline:2px solid var(--fp-accent);outline-offset:2px}
.card-workspace{display:grid;grid-template-columns:minmax(0,1fr);min-width:0}.plan-slot{height:var(--fp-stage-height,clamp(300px,calc(100dvh - 250px),680px));min-width:0;padding:16px;display:flex;align-items:center;justify-content:center;background:var(--fp-stage-background,var(--fp-soft));transition:background-color 1s ease;overflow:hidden}.plan-slot>.plan{flex:none;max-width:100%;margin:0;border-radius:10px;background:transparent}.inspector-slot{min-width:0;background:var(--fp-surface)}
.controls{padding:18px;border:0;border-top:1px solid var(--fp-line)}.inspector-heading{display:flex;gap:8px;align-items:center;margin-bottom:13px}.inspector-heading>.icon{width:18px;height:18px;color:var(--fp-accent)}.inspector-heading h3{font-size:13px;margin:0;letter-spacing:.1px;font-weight:650}.room-status{grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:5px}.room-button{padding:9px 8px 9px 30px;border:1px solid transparent;border-radius:8px;min-height:51px;background:var(--fp-soft)}.room-button strong{font-weight:600;font-size:11px}.room-button small{font-size:9px;line-height:1.45}.room-button[aria-pressed=true]{background:var(--fp-accent);color:#fff}.room-button>.icon{width:14px;left:9px}
.light-groups{gap:5px}.light-groups button{min-height:34px;padding:6px 8px;font-size:10px;border-radius:7px}.light-groups button>.icon{width:14px;height:14px}.controls p[role=status]{padding:10px 0;margin:8px 0 0;font-size:11px;color:var(--secondary-text-color,#607078)}.power-controls{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:3px}.power-controls button{min-height:38px;font-size:11px}.power-controls button:first-child{background:var(--fp-accent);color:#fff;border-color:var(--fp-accent)}.controls label{font-size:11px;font-weight:550;margin:15px 0 7px}.controls input[type=color]{height:33px;min-height:33px;padding:3px;border-radius:7px}.controls input[type=range]{height:20px;min-height:20px;margin-top:7px}.controls output{display:block;text-align:right;font-size:10px;color:var(--secondary-text-color,#607078)}.controls>.muted{font-size:10px;line-height:1.5;margin-top:15px;color:var(--secondary-text-color,#607078)}
@container(min-width:760px){.card-workspace{grid-template-columns:minmax(0,1fr) 270px}.plan-slot{height:var(--fp-stage-height,clamp(360px,calc(100dvh - 210px),760px));padding:20px}.inspector-slot{max-height:var(--fp-stage-height,clamp(360px,calc(100dvh - 210px),760px));overflow:auto;border-left:1px solid var(--fp-line)}.controls{border-top:0}.room-status{grid-template-columns:1fr}.card-header .view-modes{margin-left:auto}}
@container(max-width:440px){.card-header{padding:12px;gap:9px}.card-title h2{font-size:15px}.card-header .view-modes{width:100%;justify-content:space-between}.card-header .view-modes button{flex:1;padding:4px;font-size:9px}.plan-slot{padding:8px}.controls{padding:13px}.controls>.muted{max-width:36em}.floor-tabs button{font-size:10px;padding:5px 7px}.floor-tabs button>.icon{display:none}}

.editor{border-radius:10px;padding:16px 20px}.editor-heading{display:flex;align-items:baseline;gap:16px}.editor-heading h2{font-size:19px;letter-spacing:-.5px;margin:0}.editor-heading p{font-size:11px;margin:0}.editor nav{grid-template-columns:repeat(6,minmax(0,1fr));margin:12px 0 8px}.editor nav button{min-height:35px;padding:6px 9px;border-radius:5px}.editor-toolbar{display:flex;gap:12px;align-items:center;justify-content:space-between}.editor-toolbar>label{display:flex;gap:12px;align-items:center;font-size:11px;margin:0}.editor-toolbar>label select{width:160px;margin:0;padding:5px 8px;min-height:34px}.editor-toolbar .history-controls{margin:0}.editor-toolbar .history-controls button{min-height:32px;padding:5px 10px}
@media(max-width:600px){.editor{padding:12px}.editor nav{grid-template-columns:repeat(3,minmax(0,1fr))}.editor nav button{font-size:10px}.editor-toolbar>label{gap:5px;flex-direction:column;align-items:flex-start}.editor-toolbar>label select{width:140px}}

.light-choices{margin-top:16px}.room-button strong{font-size:12px}.room-button small{font-size:11px}.light-groups button{font-size:11px}.controls label,.controls p[role=status]{font-size:12px}.card-header .view-modes button{font-size:11px}.inspector-heading h3{font-size:15px}.card-title h2{font-size:20px}

@container(max-width:440px){.card-header .view-modes button{font-size:10px;flex-direction:column;gap:3px;white-space:normal;min-height:44px}.card-header .view-modes button>.icon{width:14px;height:14px}}
.marker.temperature-marker.temp-cool,.outdoor-temperature.temp-cool{color:#477b9b;background:#e6f1f3dd}.marker.temperature-marker.temp-warm,.outdoor-temperature.temp-warm{color:#a16644;background:#faeadddd}.marker.temperature-marker.occupied{border-left:3px solid #3b9e83;gap:4px}.temperature-marker .icon{width:13px;height:13px;color:#21886e}.plan-slot{position:relative}.plan-slot.has-outdoor{padding-left:76px}.outdoor-temperature{position:absolute;left:8px;top:44%;width:60px;white-space:normal;padding:5px 2px;font-size:10px;font-weight:500;line-height:1.5;border:0;border-radius:5px;color:var(--secondary-text-color,#617269);background:transparent;box-shadow:none}
@container(max-width:440px){.marker.temperature-marker{font-size:9px;padding:2px 3px;gap:2px}.temperature-marker .icon{width:10px;height:10px}}
/* Keep setup navigation and tools aligned across all editor sections. */
.element-palette{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin-bottom:20px}.element-palette button{justify-content:flex-start;font-size:12px;padding:9px;min-height:42px}.element-palette .icon{width:18px;height:18px}.setup-panel h3{font-size:14px;margin:0 0 10px}.connection-status{padding:10px;border-left:3px solid var(--fp-accent);background:var(--fp-soft);border-radius:4px}
@container(max-width:759px){.controls .light-choices .room-status{gap:6px}}
.controls .selection-tools button[aria-pressed=true],.controls .power-controls button:first-child{background:var(--fp-soft);color:var(--fp-accent);border-color:var(--fp-accent)}
.selection-tools{display:flex;align-items:center;gap:8px}.selection-tools>button{min-height:36px;font-size:12px}.selection-tools>button:first-child{flex:1;justify-content:center}.selection-tools>button:last-child:not(:first-child){background:transparent;border-color:transparent}
.choices-heading{font-size:11px;font-weight:650;color:var(--secondary-text-color,#607078);margin:0 0 10px;letter-spacing:.3px}
.light-choices{border-top:1px solid var(--fp-line);padding-top:16px;margin-top:16px}
.light-choices .room-status{gap:0;margin:0}.light-choices .room-button{border-radius:0;background:transparent;border-bottom:1px solid var(--fp-line);min-height:49px;padding:8px 8px 8px 28px}.light-choices .room-button[aria-pressed=true]{border-radius:6px;background:var(--fp-soft);color:var(--fp-accent);box-shadow:inset 3px 0 var(--fp-accent)}.light-choices .room-button strong{font-size:12px}.light-choices .room-button small{font-size:10px;color:var(--secondary-text-color,#607078);margin-top:3px}
.select-floor{width:100%;min-height:32px;margin:10px 0 0;font-size:11px;background:transparent}
.group-section{border-top:1px solid var(--fp-line);margin:16px 0 0;padding-top:4px}.group-section summary{font-size:12px;min-height:0;padding:12px 0;font-weight:600}.group-section>p{font-size:11px;margin:0 0 10px}.group-section .light-groups{display:grid;grid-template-columns:1fr;gap:5px}.group-section .light-groups button{width:100%;justify-content:flex-start;text-align:left;min-height:36px;font-size:11px;background:transparent}.group-section .light-groups button[aria-pressed=true]{background:var(--fp-soft);color:var(--fp-accent);border-color:var(--fp-accent)}
.controls>.inspector-heading{margin-bottom:12px}.controls>p[role=status]{margin:8px 0 0;padding:0;font-size:11px;line-height:1.5}.controls>.muted{font-size:10px;margin-top:10px}
@container(min-width:760px){.inspector-slot{overflow:hidden}.controls{box-sizing:border-box;display:flex;flex-direction:column;max-height:var(--fp-stage-height,clamp(360px,calc(100dvh - 210px),760px));height:100%}.controls>*{flex-shrink:0}.controls>.light-choices{flex:1 1 auto;min-height:80px;overflow:auto;scrollbar-gutter:stable;padding-right:4px}.controls label{margin-top:10px}.controls .power-controls{margin-top:12px}}
.editor-heading .transfer-toggle{margin-left:auto;font-size:12px;min-height:36px;white-space:nowrap}.configuration-transfer[hidden]{display:none}.configuration-transfer{padding:16px;margin:8px 0 16px;background:var(--fp-soft);border:1px solid var(--fp-line);border-radius:10px}.configuration-transfer h3{font-size:15px;margin:0 0 8px}.configuration-transfer h4{font-size:13px;margin:0}.configuration-transfer p{font-size:12px;line-height:1.5}.transfer-columns{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:16px}.transfer-columns label{font-size:12px}.configuration-transfer [role=status]{color:var(--fp-accent);font-weight:600}@media(max-width:600px){.editor-heading{flex-wrap:wrap;gap:8px}.editor-heading p{display:none}.transfer-columns{grid-template-columns:1fr;gap:16px}.editor-heading .transfer-toggle{font-size:11px}}
.setup-section{container-type:inline-size}.setup-workspace{display:grid;grid-template-columns:minmax(0,1fr) 320px;border:1px solid var(--fp-line);border-radius:12px;overflow:hidden;margin-top:14px}
.setup-canvas{padding:16px;min-width:0;background:var(--fp-soft)}.setup-canvas .plan{width:min(100%,calc(max(200px,100dvh - 405px)*var(--plan-ratio,1)));margin:0 auto}
.setup-panel{padding:16px;min-width:0;border-left:1px solid var(--fp-line);max-height:calc(100dvh - 365px);overflow:auto;scrollbar-gutter:stable}.setup-panel>label:first-child{margin-top:0}
.setup-panel label,.setup-panel p{font-size:12px}.setup-panel button{font-size:12px}.setup-panel input:not([type=range]),.setup-panel select{min-height:38px;padding:8px;font-size:12px}.setup-panel .member{align-items:flex-start;font-size:12px}.setup-panel .member button{min-height:30px;padding:5px}
@container(max-width:760px){.setup-workspace{grid-template-columns:1fr}.setup-panel{border-left:0;border-top:1px solid var(--fp-line);max-height:none;overflow:visible}.setup-canvas .plan{width:min(100%,calc(45dvh*var(--plan-ratio,1)))}}
.editor>details .plan{width:min(100%,calc(50dvh*var(--plan-ratio,1)));margin:14px auto}
.editor-heading{padding:2px 0 8px}.editor-heading h2{font-size:21px}
.editor nav{gap:4px;padding:5px;background:var(--fp-soft);border-radius:9px;margin:8px 0 14px}
.editor nav button{border-color:transparent;background:transparent;min-height:38px}
.editor nav button[aria-pressed=true]{background:var(--fp-surface);color:var(--fp-accent);border-color:var(--fp-line);box-shadow:0 1px 3px #142d2010}
.editor-toolbar{padding-bottom:12px;border-bottom:1px solid var(--fp-line)}
.editor-toolbar>label{font-size:12px}.editor-toolbar>label select{min-height:36px}
.editor label input,.editor label select{box-sizing:border-box}
.editor>.wizard-footer{padding-top:12px;margin-top:8px}.editor>details{margin:12px 0 0}
.editor>details>summary{min-height:0;padding:10px 0}
.stage-tools .overlay-toggle,.stage-tools .overlay-toggle[aria-pressed=true]{color:var(--fp-accent);background:var(--fp-surface);display:inline-flex;gap:6px;align-items:center}.stage-tools .overlay-toggle .icon{width:16px;height:16px}.stage-tools .floor-tabs button .icon{display:block;width:14px;height:14px}.stage-tools .floor-tabs button:last-child[aria-pressed=true]{box-shadow:inset 0 -2px var(--fp-accent)}
.plan-slot{padding-bottom:86px}.docked-navigation{position:absolute;bottom:10px;left:50%;transform:translateX(-50%);display:flex;gap:12px;max-width:calc(100% - 16px);padding:7px 12px;border:1px solid var(--fp-line);border-radius:12px;background:var(--fp-surface);z-index:8;box-shadow:0 2px 6px #173b2e12}.navigation-group{display:flex;flex-direction:column;gap:4px}.navigation-caption{font-size:9px;font-weight:600;color:var(--secondary-text-color,#617269);text-align:center}.navigation-buttons{display:flex;gap:4px}.docked-navigation button{min-height:34px;min-width:32px;padding:4px 8px;font-size:13px;border-radius:6px}.navigation-group+.navigation-group{border-left:1px solid var(--fp-line);padding-left:12px}@container(max-width:440px){.docked-navigation{gap:6px;padding:6px 8px}.navigation-group+.navigation-group{padding-left:6px}.docked-navigation button{min-width:30px;padding:4px 6px}}
.plan-slot{padding-top:64px}.stage-tools{position:absolute;top:10px;left:12px;right:12px;z-index:8;display:flex;align-items:center;justify-content:space-between;gap:8px}.stage-tools .floor-tabs{flex-wrap:nowrap;overflow-x:auto;max-width:100%;padding:3px;border-radius:10px;background:var(--fp-surface);box-shadow:0 1px 5px #173b2e12}.stage-tools button{white-space:nowrap}.stage-tools .overlay-toggle{font-size:11px;min-height:34px;padding:6px 10px;background:var(--fp-surface);border-color:transparent;flex-shrink:0}.stage-tools .floor-tabs button{font-size:11px;min-height:32px;padding:5px 8px}.stage-tools .floor-tabs .icon{display:none}@container(max-width:440px){.stage-tools{left:8px;right:8px;gap:5px}.stage-tools .floor-tabs button{font-size:10px;padding:5px}.stage-tools .overlay-toggle{font-size:10px;padding:5px}}

.floorplan-dashboard:not(.inspector-collapsed) .plan-slot{padding-top:108px}
/* Graphical dashboard: contextual tools, with a fully removable inspector. */
.floorplan-dashboard.inspector-collapsed .card-workspace{grid-template-columns:minmax(0,1fr)}
.inspector-slot[hidden]{display:none}
.stage-tools{justify-content:flex-start;flex-wrap:wrap}
.stage-tools .floor-tabs{margin-right:auto}
.stage-tools .stage-style{padding:0;border:0;margin:0 0 0 auto;display:block}
.stage-tools .stage-style .view-modes{width:auto;flex-wrap:nowrap;margin:0}
.stage-tools .stage-style .view-modes button{flex-direction:row;min-height:32px;font-size:11px}
.stage-tools .inspector-toggle{font-size:11px;min-height:34px;padding:6px 10px;background:var(--fp-surface);color:var(--fp-accent)}
.stage-tools .floor-tabs button .icon{display:block}
.floorplan-dashboard .plan-slot{height:var(--fp-stage-height,clamp(400px,calc(100dvh - 130px),900px))}
@container(min-width:760px){.floorplan-dashboard .inspector-slot,.floorplan-dashboard .controls{max-height:var(--fp-stage-height,clamp(400px,calc(100dvh - 130px),900px))}}
@container(max-width:759px){.floorplan-dashboard .plan-slot{padding-top:108px}.stage-tools .stage-style{flex-basis:100%;display:flex;justify-content:flex-end}.stage-tools .floor-tabs{max-width:calc(100% - 10px)} }
@media(hover:hover) and (pointer:fine){
.floorplan-dashboard .stage-tools,.floorplan-dashboard .docked-navigation,.floorplan-dashboard .marker,.floorplan-dashboard .outdoor-temperature{opacity:0;transition:opacity .25s ease .6s}
.floorplan-dashboard:hover .stage-tools,.floorplan-dashboard:hover .docked-navigation,.floorplan-dashboard:hover .marker,.floorplan-dashboard:hover .outdoor-temperature,.floorplan-dashboard:has(:focus-visible) .stage-tools,.floorplan-dashboard:has(:focus-visible) .docked-navigation,.floorplan-dashboard:has(:focus-visible) .marker,.floorplan-dashboard:has(:focus-visible) .outdoor-temperature{opacity:1;transition-delay:0s}
}
@media(prefers-reduced-motion:reduce){.floorplan-dashboard .stage-tools,.floorplan-dashboard .docked-navigation,.floorplan-dashboard .marker,.floorplan-dashboard .outdoor-temperature{transition:none}}

.display-settings{margin:0;position:relative;font-size:11px;flex-shrink:0}
.display-settings>summary{box-sizing:border-box;min-height:34px;cursor:pointer;list-style:none;padding:9px 12px;border-radius:8px;background:var(--fp-surface);color:var(--fp-accent)}
.stage-tools:has(.display-settings[open]){z-index:10}
.display-popover{box-sizing:border-box;position:absolute;top:calc(100% + 8px);right:0;width:235px;padding:14px;border:1px solid var(--fp-line);border-radius:12px;background:var(--fp-surface);box-shadow:0 8px 24px #0003;max-height:60vh;overflow:auto}
.display-popover label{font-size:12px}.display-popover select{width:100%;font-size:12px}.display-popover p{font-size:11px}
.floorplan-dashboard .marker{scale:var(--fp-marker-scale,.8)}
.floorplan-dashboard[data-lights=hidden] .overlay-lights,.floorplan-dashboard[data-temperatures=hidden] .overlay-temperatures,.floorplan-dashboard[data-temperatures=hidden] .outdoor-temperature,.floorplan-dashboard[data-heating=hidden] .overlay-heating{display:none}
.floorplan-dashboard[data-lights=always] .overlay-lights,.floorplan-dashboard[data-temperatures=always] .overlay-temperatures,.floorplan-dashboard[data-temperatures=always] .outdoor-temperature,.floorplan-dashboard[data-heating=always] .overlay-heating,.floorplan-dashboard[data-controls=always] .stage-tools,.floorplan-dashboard[data-controls=always] .docked-navigation,.floorplan-dashboard:has(.display-settings[open]) .stage-tools{opacity:1;transition-delay:0s}
@container(max-width:759px){.floorplan-dashboard .plan-slot{padding-top:150px}.stage-tools .floor-tabs{flex-basis:auto;margin:0 auto 0 0}.stage-tools .stage-style{flex-basis:auto;margin-left:auto}.docked-navigation{gap:4px;padding:6px}.navigation-group+.navigation-group{padding-left:4px}.docked-navigation button{min-width:27px;padding:4px}.display-settings{position:static}.display-popover{right:0;left:auto;top:calc(100% + 6px);width:min(280px,100%)}}

/* A quiet entrance and progressive hover disclosure. */
@keyframes floorplan-arrive{from{opacity:0}to{opacity:1}}
@keyframes model-arrive{from{opacity:0;rotate:-1.5deg;scale:.98}to{opacity:1;rotate:0deg;scale:1}}
.floorplan-dashboard.has-entered{animation:floorplan-arrive .65s ease both}
.floorplan-dashboard.has-entered .plan{animation:model-arrive 1.1s cubic-bezier(.2,.7,.2,1) both}
.stage-tools .overlay-toggle,.stage-tools .inspector-toggle{font-size:0;width:36px;min-width:36px;padding:8px;justify-content:center}
.stage-tools .overlay-toggle .icon,.stage-tools .inspector-toggle .icon{width:18px;height:18px}
.docked-navigation .navigation-caption{display:none}
.docked-navigation{padding:6px 8px;gap:8px;border-radius:10px;box-shadow:0 3px 12px #173b2e10}
.docked-navigation button{font-size:12px;min-height:32px}
.display-popover .check{display:flex;align-items:center;gap:8px}.display-popover .check input{width:16px;min-height:16px;margin:0}
@media(hover:hover) and (pointer:fine){
.floorplan-dashboard .stage-tools,.floorplan-dashboard .docked-navigation,.floorplan-dashboard .marker,.floorplan-dashboard .outdoor-temperature{transition:opacity .4s ease .2s}
.floorplan-dashboard:hover .stage-tools{transition-delay:.06s}
.floorplan-dashboard:hover .docked-navigation{transition-delay:.2s}
.floorplan-dashboard:hover .marker,.floorplan-dashboard:hover .outdoor-temperature{transition-delay:.4s}
}
@media(prefers-reduced-motion:reduce){.floorplan-dashboard.has-entered,.floorplan-dashboard.has-entered .plan{animation:none}.floorplan-dashboard .stage-tools,.floorplan-dashboard .docked-navigation,.floorplan-dashboard .marker,.floorplan-dashboard .outdoor-temperature{transition:none}}

.stage-tools{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:10px;align-items:start}
.stage-tools>.floor-tabs{justify-self:start;margin:0;max-width:100%}
.stage-tools>.stage-style{justify-self:end;margin:0}
.stage-utilities{position:relative;display:flex;align-items:center;gap:6px;justify-self:center}
.stage-utilities .display-settings{position:static}
.stage-utilities .display-settings>summary,.stage-utilities>.overlay-toggle,.stage-utilities>.inspector-toggle{display:flex;align-items:center;justify-content:center;width:36px;height:36px;min-height:36px;min-width:36px;padding:8px;box-sizing:border-box;border:1px solid transparent;border-radius:8px;background:var(--fp-surface);color:var(--fp-accent)}
.display-settings>summary::-webkit-details-marker{display:none}
.stage-utilities>.overlay-toggle,.stage-utilities>.inspector-toggle{gap:0}
.stage-utilities .icon{width:18px;height:18px;flex-shrink:0}
.stage-utilities button:hover,.display-settings>summary:hover,.display-settings[open]>summary{background:var(--fp-soft);border-color:var(--fp-line)}
.display-settings>summary:focus-visible{outline:2px solid var(--fp-accent);outline-offset:2px}
.stage-utilities .display-popover{left:50%;right:auto;transform:translateX(-50%);width:280px;max-width:calc(100vw - 32px);padding:16px;color:var(--primary-text-color,#26343d);background:var(--fp-surface);border-color:var(--fp-line);box-shadow:0 8px 24px #132b3326;max-height:min(540px,calc(var(--fp-stage-height,70dvh) - 120px))}
.display-popover h3{font-size:14px;margin:0 0 5px;font-weight:650}
.display-popover .display-description{margin:0 0 14px;color:var(--secondary-text-color,#617269);line-height:1.5}
.display-popover label{font-size:12px;font-weight:550;margin:12px 0;color:inherit}
.display-popover select{appearance:none;font-family:inherit;font-size:12px;min-height:36px;padding:8px 30px 8px 10px;border-color:var(--fp-line);background-color:var(--fp-soft);color:var(--primary-text-color,#26343d);background-image:linear-gradient(45deg,transparent 50%,currentColor 50%),linear-gradient(135deg,currentColor 50%,transparent 50%);background-position:calc(100% - 15px) 15px,calc(100% - 11px) 15px;background-size:4px 4px;background-repeat:no-repeat}
.display-popover select:focus-visible{outline:2px solid var(--fp-accent);outline-offset:2px}
.display-popover .check{justify-content:space-between;border-bottom:1px solid var(--fp-line);padding-bottom:14px;margin-bottom:16px}
.display-popover .check input{appearance:none;position:relative;flex:none;width:32px!important;height:18px;min-height:18px;padding:0;border:0;border-radius:12px;background:var(--fp-line);cursor:pointer;transition:background .2s}
.display-popover .check input:before{content:'';position:absolute;top:3px;left:3px;width:12px;height:12px;border-radius:50%;background:var(--fp-surface);transition:transform .2s}
.display-popover .check input:checked{background:var(--fp-accent)}.display-popover .check input:checked:before{transform:translateX(14px)}
.display-popover input[type=range]{accent-color:var(--fp-accent)}
.display-popover>p:last-child{border-top:1px solid var(--fp-line);padding-top:12px;margin:14px 0 0;color:var(--secondary-text-color,#617269);line-height:1.5}
@container(max-width:1050px){.stage-tools{grid-template-columns:1fr 1fr}.stage-tools>.floor-tabs{grid-column:1/-1}.stage-utilities{justify-self:start}.stage-tools>.stage-style{grid-column:2;justify-self:end}.stage-utilities .display-popover{left:0;transform:none}.floorplan-dashboard .plan-slot{padding-top:108px}}
@container(max-width:440px){.stage-tools{gap:8px 4px}.stage-utilities{gap:4px}.stage-tools .stage-style .view-modes select{min-width:90px}.stage-tools .stage-style .view-modes button{padding:5px}.stage-utilities .display-popover{width:280px}}
@media(prefers-reduced-motion:reduce){.display-popover .check input,.display-popover .check input:before{transition:none}}

/* WebGL extends behind the floating tools instead of clipping at their gutters. */
.plan-slot.has-3d-canvas>.plan-3d{position:absolute!important;inset:0;border-radius:0;max-width:none}
`;
